### ISSUE TITLE
Bayonetta 2

### ISSUE THREAD

**Issue by bloedmage** [SamoZ256/cemu-metal-game-compatibility#43]
## Description

Flickering effect on main characters faces and hair. Also on some geometry. This is also present in the main release of CEMU using MoltenVK 

## Screenshots

![Screenshot 2024-11-24 at 12 17 49](https://github.com/user-attachments/assets/fd506612-8d02-43b5-9c7b-d898d74cd557)

![Screenshot 2024-11-24 at 12 22 12](https://github.com/user-attachments/assets/54ccc014-0742-4ae2-8fc2-306c95e3cec0)

![Screenshot 2024-11-24 at 12 22 32](https://github.com/user-attachments/assets/e7b9921e-1cc1-4d15-8ca4-70cd2639043b)

## Cemu Metal version

Cemu testing1.0.6

## Mac

Mac Pro 2013 running macOS Ventura 13.7.1 using OpenCore Legacy Patcher

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet.

**Comment by bloedmage** [comment]
Impressive Performance gain going from vulkan to metal. From slightly above 40 to almost 60fps. Metal renderer is slightly less vibrant though. This is with 2020 MacBook Pro 13 inch with intel iris G7 graphics. 

![Screenshot 2024-11-24 at 23 35 13](https://github.com/user-attachments/assets/f1ef90b4-ce02-4d68-97f3-62d702429ddb)
![Screenshot 2024-11-24 at 23 33 59](https://github.com/user-attachments/assets/5b99f0c4-3506-479a-b58c-94063d7601ff)

**Comment by SamoZ256** [comment]
Good to hear that the performance is great. The color difference might be an srgb problem, though I think it would be more severe in that case

**Comment by shinra-electric** [comment]
The position invariance option from [this build](https://github.com/SamoZ256/cemu-metal-game-compatibility/issues/26#issuecomment-2551647134) fixes most of the issues. It is very playable now.

**Issues fixed:**
The striping/stippling on surfaces are fixed:
![Screenshot 2024-12-18 at 16 09 39](https://github.com/user-attachments/assets/6ed35639-7619-470f-8599-9464d604d4e5)


Black/white flickering on faces are fixed. 
![Screenshot 2024-12-18 at 16 17 12](https://github.com/user-attachments/assets/727df7b0-4c93-43b5-9954-12e6d342d029)
![Screenshot 2024-12-18 at 16 16 25](https://github.com/user-attachments/assets/2b8d1fe7-50ec-4d43-88a9-8be28f72ae71)

**Issues remaining:**
I noticed one area where the flickering still remains, on a TV billboard in the intro:
(It doesn't show so well in this screenshot, but it's there)
![Screenshot 2024-12-18 at 16 15 35](https://github.com/user-attachments/assets/69c4ee7e-08b6-4ed3-a95d-8d59c4f35452)

Also there are some effects like particles that are shown as squares rather than whatever shape they are supposed to be.
![Screenshot 2024-12-18 at 16 26 17](https://github.com/user-attachments/assets/1e6cda36-503e-4515-a3b2-6d3799b0e31f)
![Screenshot 2024-12-18 at 16 22 43](https://github.com/user-attachments/assets/45ae2785-183e-46f4-952c-7805fdc3eee8)

**Comment by SamoZ256** [comment]
Thank you for the detailed report! At least it's playable now

**Comment by shinra-electric** [comment]
Here is a GPU trace for the square particles on the title screen:
https://file.io/nHX95YukYgMw

**Comment by SamoZ256** [comment]
@shinra-electric [this build](https://drive.google.com/file/d/1TV4HE9BzWZOhcT5fsx5ZFfEXcRtxjnp2/view?usp=sharing) should fix the box particles

**Comment by shinra-electric** [comment]
Square particles fixed:
<img width="1392" alt="Screenshot 2024-12-21 at 10 48 05" src="https://github.com/user-attachments/assets/95ac7be7-b993-4d42-a9bd-10cf67db9464" />
<img width="1392" alt="Screenshot 2024-12-21 at 10 44 20" src="https://github.com/user-attachments/assets/4216326a-6693-4b25-a094-16eafe1a312b" />

**Comment by shinra-electric** [comment]
The issue on the billboard is there on Vulkan as well, so this one should probably be tagged as perfect too.

**Comment by SamoZ256** [comment]
If there is flickering, I won’t label it as perfect. Do you know if the flickering on billboard happens on Windows as well? If yes, we can probably close this issue

**Comment by shinra-electric** [comment]
> Do you know if the flickering on billboard happens on Windows as well? 

I don’t have Windows to test.

**Comment by SamoZ256** [comment]
Alright, I will close this, it's a small issue anyways
